FROM node:18-slim

# Copia los archivos del frontend al directorio raíz de Nginx
COPY public /usr/share/nginx/html

# Copia el archivo de configuración personalizado de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expone el puerto 80
EXPOSE 80