# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración de npm (package.json y package-lock.json)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del backend al directorio de trabajo
COPY . .

# Expone el puerto (si es necesario)
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]